CREATE TABLE IF NOT EXISTS "Employees" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT NOT NULL CHECK (LENGTH(Name) <= 70),
	"PositionId" INTEGER REFERENCES Positions ON DELETE SET NULL ON UPDATE CASCADE,
	"Salary" REAL CHECK (Salary >= 0),
	"Email" TEXT CHECK (LENGTH(Email) <= 255),
	"Photo" BLOB,
	"StoreId" INTEGER REFERENCES Stores ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Products" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT NOT NULL,
	"CategoryId" INTEGER REFERENCES Categories ON DELETE SET NULL ON UPDATE CASCADE,
	"Price" REAL NOT NULL CHECK (Price >= 0),
	"Stock" INTEGER NOT NULL CHECK (Stock >= 0)
);

CREATE TABLE IF NOT EXISTS "Customers" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT CHECK (LENGTH(Name) <= 70),
	"Email" TEXT CHECK (LENGTH(Email) <= 254),
	"PhoneNumber" TEXT CHECK (LENGTH(PhoneNumber) <= 15),
	"Address" TEXT CHECK (LENGTH(Address) <= 200)
);

CREATE TABLE IF NOT EXISTS "Orders" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Date" DATE NOT NULL,
	"CustomerId" INTEGER REFERENCES Customers ON DELETE SET NULL ON UPDATE CASCADE,
	"TotalAmount" REAL CHECK(TotalAmount >= 0)
);

CREATE TABLE IF NOT EXISTS "ProductOrders" (
	"OrderId" INTEGER NOT NULL REFERENCES Orders,
	"ProductId" INTEGER NOT NULL REFERENCES Products,
	"Quantity" INTEGER NOT NULL,
    "PriceAtOrder" REAL NOT NULL,
    PRIMARY KEY ("OrderId", "ProductId")
);

CREATE TABLE IF NOT EXISTS "Categories" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT NOT NULL UNIQUE CHECK(LENGTH(Name) <= 25)
);

CREATE TABLE IF NOT EXISTS "Stores" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Address" TEXT CHECK (LENGTH(Address) <= 200),
	"ManagerId" INTEGER REFERENCES Employees ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Positions" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT NOT NULL UNIQUE CHECK(LENGTH(Name) <= 25)
);
