CREATE TABLE IF NOT EXISTS "Employees" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT,
	"PositionId" INTEGER REFERENCES Positions ON DELETE SET NULL ON UPDATE CASCADE,
	"Salary" REAL,
	"Email" TEXT,
	"Photo" BLOB,
	"StoreId" INTEGER NOT NULL REFERENCES Stores ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Products" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT,
	"CategoryId" INTEGER REFERENCES Categories ON DELETE SET NULL ON UPDATE CASCADE,
	"Price" REAL NOT NULL CHECK (Price >= 0),
	"Stock" INTEGER NOT NULL CHECK (Stock >= 0)
);

CREATE TABLE IF NOT EXISTS "Customers" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" VARCHAR,
	"Email" VARCHAR,
	"PhoneNumber" VARCHAR,
	"Adress" INTEGER
);

CREATE TABLE IF NOT EXISTS "Orders" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Date" DATE,
	"CustomerId" INTEGER REFERENCES Customers ON DELETE SET NULL ON UPDATE CASCADE,
	"TotalAmount" REAL
);

CREATE TABLE IF NOT EXISTS "ProductOrders" (
	"OrderId" INTEGER NOT NULL REFERENCES Orders,
	"ProductId" INTEGER NOT NULL REFERENCES Products,
	"Quantity" INTEGER NOT NULL,
    "PriceAtOrder" REAL NOT NULL,
    PRIMARY KEY ("OrderId", "ProductId")
);

CREATE TABLE IF NOT EXISTS "Categories" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" VARCHAR
);

CREATE TABLE IF NOT EXISTS "Stores" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Adress" TEXT,
	"ManagerId" INTEGER REFERENCES Employees
);

CREATE TABLE IF NOT EXISTS "Positions" (
	"Id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
	"Name" TEXT
);
